### ISSUE TITLE
OpenCTI analyzers not working

### ISSUE THREAD

**Issue by bakhtawarw** [TheHive-Project/Cortex-Analyzers#1122]
**Describe the bug**
I enabled opencti analyzers in cortex but I'm getting the following error for both of the analyzers.

Traceback (most recent call last):
  File "/worker/OpenCTI/opencti.py", line 111, in <module>
    OpenCTIAnalyzer().run()
  File "/worker/OpenCTI/opencti.py", line 97, in run
    del(report["x_opencti_graph_data"])
KeyError: 'x_opencti_graph_data'
Killed

**To Reproduce**
1. Run analyzer on observavble.

**Expected behavior**
Report about the observable from opencti.

**Work environment**
 - 2 Ubuntu 20.04 Virtual machines. Cortex is deployed on one vm and opencti on another.
 
 - Browse type and version:
- Cortex version: 3.1.6-1
 - Cortex Analyzer/Responder name:  OpenCTI_SearchObservables_2_0 & OpenCTI_SearchExactObservable_2_0
- Opencti version : 5.3.7

**Comment by SamuelHassine** [comment]
Just need a new tag here to take into account the new version of the Python library in the analyzer.

**Comment by igcoser** [comment]
Make sure that you are not accessing  # del (report["x_opencti_graph_data"]) in your analyzer.
