### ISSUE TITLE
[Bug] CrowdSec Analyzer: requests module missing

### ISSUE THREAD

**Issue by ebdavison** [TheHive-Project/Cortex-Analyzers#1227]
**Describe the bug**
Running crowdsec analyzer results in an error.

Error:
```
Traceback (most recent call last):
  File "/worker/Crowdsec/crowdsec_analyzer.py", line 4, in <module>
    from crowdsec_api import Crowdsec
  File "/worker/Crowdsec/crowdsec_api.py", line 2, in <module>
    from requests.compat import urljoin
ModuleNotFoundError: No module named 'requests'
```

**To Reproduce**
1. enable crowdsec analyzer
1. run crowdsec analyzer

**Expected behavior**
Proper results from the use of the crowdsec analyzer

**Complementary information**
If applicable, add screenshots and any additional information that might help explain your problem.

**Work environment**
 - Client OS: fedora linux
- Server OS: fedora linux / docker install
 - Browse type and version: firefox 118.0.1 (64-bit)
- Cortex version: 
 - Cortex Analyzer/Responder name: CrowdSec Analyzer
- Cortex Analyzer/Responder version: 1.0

**Possible solutions**
If applicable, indicate possible solutions to the problem.

**Additional context**

**Comment by LaurenceJJones** [comment]
Linked to #1224
