### ISSUE TITLE
Bluecoat Categorization failes with Cortex2

### ISSUE THREAD

**Issue by crackytsi** [TheHive-Project/Cortex-Analyzers#216]
### Request Type
Bug 

### Work Environment
| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian, Ubuntu, CentOS, RedHat, ...
| OS version (client)       | Seven
| Cortex Analyzer Name      | BlueCoat_Categorization_1_0
| Cortex Analyzer Version   | 1.9 (latest from today)
| Cortex Version            | 2.0.1

### Description
BlueCoat analyzers failes 

### Steps to Reproduce
1. Install Cortex2
1. Install latest CortexAnalyzers
1. Run BlueCoat Analysis with Cortex2 for domain: www.google.de

### Complementary information
```
Invalid output
Traceback (most recent call last):
  File "Bluecoat/categorization.py", line 53, in call_bluecoat_api
    return json.loads(BC_json_answer.text)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Bluecoat/categorization.py", line 108, in <module>
    BluecoatAnalyzer().run()
  File "Bluecoat/categorization.py", line 91, in run
    json_answer = self.call_bluecoat_api(self.get_data())
  File "Bluecoat/categorization.py", line 55, in call_bluecoat_api
    self.error(e)
  File "/usr/local/lib/python3.4/dist-packages/cortexutils/analyzer.py", line 182, in error
    ensure_ascii=ensure_ascii)
  File "/usr/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ValueError('Expecting value: line 1 column 1 (char 0)',) is not JSON serializable
{"errorMessage": 

```

**Comment by nadouani** [comment]
Well looks like Bluecoat is returning something like:

```
<html>

<head>
  <title>Apache Tomcat/7.0.52 (Ubuntu) - Error report</title>
  <style>
    ...
  </style>
</head>

<body>
  <h1>HTTP Status 403 - Security violation.</h1>
  <HR size="1" noshade="noshade">
  <p><b>type</b> Status report</p>
  <p><b>message</b> <u>Security violation.</u></p>
  <p><b>description</b> <u>Access to the specified resource has been forbidden.</u></p>
  <HR size="1" noshade="noshade">
  <h3>Apache Tomcat/7.0.52 (Ubuntu)</h3></body>

</html>
```

which is not what the analyzer expects.

Two questions:
- Is the API used by the analyzer still valid?
- Should the analyzer handle the 403 error?

**Comment by nadouani** [comment]
BTW, This is not related to Cortex 2.0.0

**Comment by 3c7** [comment]
Symantec added Javascript to the site that prevents the analyzer from working. Querying Bluecoat using curl in the previous successful manner is currently not possible, too. Bad timing. Need to check, if we can fix it.

**Comment by saadkadhi** [comment]
If we can't fix it, we need to ax it.

**Comment by 3c7** [comment]
Actually, querying Symantecs Sitereview is against their ToS. So, for now, I'll remove the analyzer. Fortinet can be used for website categorization anyway.
