### ISSUE TITLE
Analyzer Issue : Abuse_Finder 

### ISSUE THREAD

**Issue by jipidini** [TheHive-Project/Cortex-Analyzers#277]
### Request Type
Analyzer

### Work Environment
N/A

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | OSX
| Cortex Analyzer Name      | Abuse_Finder 
| Cortex Analyzer Version   | 2.0
| Cortex Version            | 2.0.4
| Browser type & version    | Chrome

### Description
Submitting a job using the using the Abuse_Finder analyzer

### Steps to Reproduce
(keep this section only if the issue relates to a bug)
1. Logged In Cortex
2. \+ New Analysis
3. ip, 8.8.8.8, Abuse_Finder

```
Invalid output
/usr/local/lib/python2.7/dist-packages/ipwhois/net.py:138: UserWarning: allow_permutations has been deprecated and will be removed. It is no longer needed, due to the deprecation of asn_alts, and the addition of the asn_methods argument.
  warn('allow_permutations has been deprecated and will be removed. '
/usr/local/lib/python2.7/dist-packages/ipwhois/asn.py:178: UserWarning: IPASN._parse_fields_dns() has been deprecated and will be removed. You should now use IPASN.parse_fields_dns().
  warn('IPASN._parse_fields_dns() has been deprecated and will be '
Traceback (most recent call last):
  File "Abuse_Finder/abusefinder.py", line 44, in <module>
    AbuseFinderAnalyzer().run()
  File "Abuse_Finder/abusefinder.py", line 40, in run
    self.report({'abuse_finder': self.abuse()})
  File "Abuse_Finder/abusefinder.py", line 29, in abuse
    return ip_abuse(self.get_data())
  File "/usr/local/lib/python2.7/dist-packages/abuse_finder/ip.py", line 43, in ip_abuse
    results = obj.lookup_whois(inc_raw=True)
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/ipwhois.py", line 179, in lookup_whois
    field_list=field_list
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/whois.py", line 678, in lookup
    extra_blacklist=extra_blacklist
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 649, in get_whois
    server=server, port=port, extra_blacklist=extra_blacklist
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 649, in get_whois
    server=server, port=port, extra_blacklist=extra_blacklist
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 649, in get_whois
    server=server, port=port, extra_blacklist=extra_blacklist
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 655, in get_whois
    'WHOIS lookup failed for {0}.'.format(self.address_str)
ipwhois.exceptions.WhoisLookupError: WHOIS lookup failed for 8.8.8.8.
```

### Possible Solutions
Still researching...

**Comment by saadkadhi** [comment]
Weird. I just did the same and it works perfectly:
<img width="222" alt="screen shot 2018-06-07 at 23 11 36" src="https://user-images.githubusercontent.com/2852427/41126549-2e563d14-6aa8-11e8-89a2-04bcc5ba93ba.png">
<img width="1294" alt="screen shot 2018-06-07 at 23 11 17" src="https://user-images.githubusercontent.com/2852427/41126551-31db14dc-6aa8-11e8-82f4-51dd2d6768f4.png">

**Comment by jipidini** [comment]
ok thanks! Weird indeed... I have built another instance on a different machine and get the same error:

```
Invalid output
/usr/local/lib/python2.7/dist-packages/ipwhois/net.py:138: UserWarning: allow_permutations has been deprecated and will be removed. It is no longer needed, due to the deprecation of asn_alts, and the addition of the asn_methods argument.
  warn('allow_permutations has been deprecated and will be removed. '
/usr/local/lib/python2.7/dist-packages/ipwhois/asn.py:178: UserWarning: IPASN._parse_fields_dns() has been deprecated and will be removed. You should now use IPASN.parse_fields_dns().
  warn('IPASN._parse_fields_dns() has been deprecated and will be '
Traceback (most recent call last):
  File "Abuse_Finder/abusefinder.py", line 44, in <module>
    AbuseFinderAnalyzer().run()
  File "Abuse_Finder/abusefinder.py", line 40, in run
    self.report({'abuse_finder': self.abuse()})
  File "Abuse_Finder/abusefinder.py", line 29, in abuse
    return ip_abuse(self.get_data())
  File "/usr/local/lib/python2.7/dist-packages/abuse_finder/ip.py", line 43, in ip_abuse
    results = obj.lookup_whois(inc_raw=True)
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/ipwhois.py", line 179, in lookup_whois
    field_list=field_list
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/whois.py", line 678, in lookup
    extra_blacklist=extra_blacklist
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 649, in get_whois
    server=server, port=port, extra_blacklist=extra_blacklist
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 649, in get_whois
    server=server, port=port, extra_blacklist=extra_blacklist
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 649, in get_whois
    server=server, port=port, extra_blacklist=extra_blacklist
  File "/usr/local/lib/python2.7/dist-packages/ipwhois/net.py", line 655, in get_whois
    'WHOIS lookup failed for {0}.'.format(self.address_str)
ipwhois.exceptions.WhoisLookupError: WHOIS lookup failed for 8.8.8.8.
```

<img width="516" alt="screen shot 2018-06-08 at 3 33 50 pm" src="https://user-images.githubusercontent.com/7275204/41177283-76d23802-6b31-11e8-96cf-db6f2012caab.png">

**Comment by jeromeleonard** [comment]
Never got this message while running the analyzer. This seems to be related to a known issue in _ipwhois_ lib used by _abuse_finder_ library : [https://github.com/secynic/ipwhois/issues/203](https://github.com/secynic/ipwhois/issues/203) . 

I also made some tests and managed to get the error sometimes.

```
>>> from ipwhois import IPWhois
>>> obj = IPWhois('8.8.8.8')
/usr/local/lib/python2.7/site-packages/ipwhois/net.py:138: UserWarning: allow_permutations has been deprecated and will be removed. It is no longer needed, due to the deprecation of asn_alts, and the addition of the asn_methods argument.
  warn('allow_permutations has been deprecated and will be removed. '
>>> obj = IPWhois('8.8.8.8')
>>> obj = IPWhois('8.8.4.4')
>>>
```

**Comment by saadkadhi** [comment]
@jeromeleonard should we close this one or are you still looking into it?

**Comment by hermanmaleiane** [comment]
Hi @jeromeleonard and @saadkadhi!!!
I have this issue using Abuse_Finder 3 docker neurons.
How can i fix this?

![image](https://user-images.githubusercontent.com/13849459/113974521-59633400-983e-11eb-95c7-3c7366831156.png)
