### ISSUE TITLE
Cuckoo Sandbox Analyzer error

### ISSUE THREAD

**Issue by 1623664** [TheHive-Project/Cortex-Analyzers#458]
Hi,
Question | Answer
-- | --
OS version (server) | CentOS 7 (Running Cortex in Docker )
OS version (client) | NA
Cortex Analyzer Name | CuckooSandbox_File_Analysis_Inet_1_1
Cortex Version | 2.1.2

![Снимок экрана от 2019-04-11 16-44-29](https://user-images.githubusercontent.com/18025686/55962334-50ecb880-5c79-11e9-9bd2-723efdfe84fc.png)

**Comment by 1623664** [comment]
[INFO] from org.thp.cortex.services.ErrorHandler in application-akka.actor.default-dispatcher-84 - GET /api/analyzer/CuckooSandbox_File_Analysis_Inet_1_1 return$
org.elastic4play.NotFoundError: worker CuckooSandbox_File_Analysis_Inet_1_1 not found
        at org.thp.cortex.services.WorkerSrv.$anonfun$getForOrganization$2(WorkerSrv.scala:103)
        at scala.Option.getOrElse(Option.scala:121)
        at org.thp.cortex.services.WorkerSrv.$anonfun$getForOrganization$1(WorkerSrv.scala:103)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by ArnaudLoos** [comment]
In your Cortex-Analyzers/analyzers directory do you have CuckooSandbox/cuckoosandbox_analyzer.py?  Can you run update_catalogs.sh in the Cortex-Analyzers directory? Maybe update Cortex to 2.1.3?
I'm assuming your Cuckoo box is up and running just fine but I'll post a link here to my Cuckoo installation tutorial just in case. I just got this integration working this week with Cortex 2.1.3.
https://arnaudloos.com/2019/cuckoo-sandbox-installation/

**Comment by 1623664** [comment]
Thank. Upgrading to version 2.1.3 solved the problem.
