### ISSUE TITLE
FileInfo_5_0 Cannot parse PDF files

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/Cortex-Analyzers#495]
I am receiving the following error when trying to parse a pdf file:

```
Invalid output
Traceback (most recent call last):
  File "FileInfo/fileinfo_analyzer.py", line 76, in <module>
    FileInfoAnalyzer().run()
  File "FileInfo/fileinfo_analyzer.py", line 65, in run
    module_summaries = module.module_summary()
  File "/opt/Cortex-Analyzers/analyzers/FileInfo/submodules/submodule_pdfid.py", line 31, in module_summary
    for subsection in section['submodule_section_content']:
TypeError: 'AttributeError' object is not iterable
```

**Comment by robertnixon2003** [comment]
Also why is there two FileInfo analyzers? File_Info and FileInfo

**Comment by jeromeleonard** [comment]
Could you please tell me if this error still exist in FileInfo_6_0  ? 
If so, and if the document is not confidential, could you share its hash as I can do some tests on my side.
Thx.

**Comment by jeromeleonard** [comment]
@robertnixon2003 what about this bug in latest version of FileInfo ?

**Comment by jeromeleonard** [comment]
no answer.
