### ISSUE TITLE
[Bug] VMRay Returns Error

### ISSUE THREAD

**Issue by mpgough** [TheHive-Project/Cortex-Analyzers#520]
When uploading a exe the following error is returned:

```
Invalid output
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "VMRay/vmray.py", line 103, in <module>
    VMRayAnalyzer().run()
  File "VMRay/vmray.py", line 30, in __init__
    reanalyze=reanalyze)
  File "/opt/Cortex-Analyzers/analyzers/VMRay/vmrayclient.py", line 51, in __init__
    if cert and os.path.isfile(cert):
  File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, bool found
```

**Comment by dadokkio** [comment]
Hi, looking just at the code it seems something related tovanalyzer configuration. 
The error should be present if the "certpath" is missing but "certverify" flag is set to True.
Can you confirm? If this is true you should resolve the issue just turning the "certverify" flat to False

**Comment by jeromeleonard** [comment]
@mpgough please reopen that issue if the bug is not fixed
