### ISSUE TITLE
[Bug] Yeti Analyzer docker images pip installing pyeti

### ISSUE THREAD

**Issue by asucrews** [TheHive-Project/Cortex-Analyzers#708]
**Describe the bug**

Looks like docker image  pip installing pyeti

2020-03-04 22:11:37,776 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-87 - Job AXCnmqjWXsbgdWPRkHNu has be updated (JsDefined("InProgress"))
2020-03-04 22:11:37,776 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in application-akka.actor.default-dispatcher-83 - Execute /opt/Cortex-Analyzers/analyzers/Yeti/yeti.py in /opt/Cortex-Analyzers/analyzers, timeout is 30 minutes
2020-03-04 22:11:37,859 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-38 -   Job AXCnmqjWXsbgdWPRkHNu: Traceback (most recent call last):
2020-03-04 22:11:37,859 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-38 -   Job AXCnmqjWXsbgdWPRkHNu:   File "/opt/Cortex-Analyzers/analyzers/Yeti/yeti.py", line 3, in <module>
2020-03-04 22:11:37,859 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-38 -   Job AXCnmqjWXsbgdWPRkHNu:     import pyeti
2020-03-04 22:11:37,859 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-38 -   Job AXCnmqjWXsbgdWPRkHNu: ModuleNotFoundError: No module named 'pyeti'
2020-03-04 22:11:38,785 [INFO] from org.thp.cortex.services.JobSrv in application-akka.actor.default-dispatcher-87 - Job AXCnmqjWXsbgdWPRkHNu has finished with status Failure
2020-03-04 22:11:38,785 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-87 - Job AXCnmqjWXsbgdWPRkHNu has be updated (JsDefined("Failure"))

**To Reproduce**
1. emable yeti analyzer
2. create new  analysis

**Expected behavior**

Return hit from yeti

**Complementary information**
If applicable, add screenshots and any additional information that might help explain your problem.

2020-03-04 22:11:37,776 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-87 - Job AXCnmqjWXsbgdWPRkHNu has be updated (JsDefined("InProgress"))
2020-03-04 22:11:37,776 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in application-akka.actor.default-dispatcher-83 - Execute /opt/Cortex-Analyzers/analyzers/Yeti/yeti.py in /opt/Cortex-Analyzers/analyzers, timeout is 30 minutes
2020-03-04 22:11:37,859 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-38 -   Job AXCnmqjWXsbgdWPRkHNu: Traceback (most recent call last):
2020-03-04 22:11:37,859 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-38 -   Job AXCnmqjWXsbgdWPRkHNu:   File "/opt/Cortex-Analyzers/analyzers/Yeti/yeti.py", line 3, in <module>
2020-03-04 22:11:37,859 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-38 -   Job AXCnmqjWXsbgdWPRkHNu:     import pyeti
2020-03-04 22:11:37,859 [INFO] from org.thp.cortex.services.ProcessJobRunnerSrv in Thread-38 -   Job AXCnmqjWXsbgdWPRkHNu: ModuleNotFoundError: No module named 'pyeti'
2020-03-04 22:11:38,785 [INFO] from org.thp.cortex.services.JobSrv in application-akka.actor.default-dispatcher-87 - Job AXCnmqjWXsbgdWPRkHNu has finished with status Failure
2020-03-04 22:11:38,785 [INFO] from org.thp.cortex.services.AuditActor in application-akka.actor.default-dispatcher-87 - Job AXCnmqjWXsbgdWPRkHNu has be updated (JsDefined("Failure"))

**Work environment**
 - Client OS:  windows
- Server OS: ubuntu 18.04
 - Browse type and version: chrome 
- Cortex version: Version 80.0.3987.122 (Official Build) (64-bit)
 - Cortex Analyzer/Responder name: yeti
- Cortex Analyzer/Responder version: latest

**Possible solutions**
If applicable, indicate possible solutions to the problem.

add pip install pyeti within docker.

**Additional context**

**Comment by dadokkio** [comment]
@asucrews probably the error was that the docker was installing pyeti library for python2 while the analyzer was running python3.
Can you please check if the proposed fix resolve it?

**Comment by asucrews** [comment]
Yes this work! thanks!

**Comment by garanews** [comment]
fixed in 2.7.0
