### ISSUE TITLE
Abuse_Finder_3_0 [KeyError: '\\s']

### ISSUE THREAD

**Issue by BaldrIronborn** [TheHive-Project/Cortex-Analyzers#940]
**Describe the bug**
Does not work Abuse_Finder_3_0.

Traceback (most recent call last): File "/usr/lib/python3.8/sre_parse.py", line 1039, in parse_template this = chr(ESCAPES[this][1])KeyError: '\\s'During handling of the above exception, another exception occurred:Traceback (most recent call last): File "/opt/cortex-analyzers/analyzers/Abuse_Finder/abusefinder.py", line 9, in <module> from abuse_finder import domain_abuse, ip_abuse, \ File "/usr/local/lib/python3.8/dist-packages/abuse_finder/__init__.py", line 2, in <module> from .domain import domain_abuse File "/usr/local/lib/python3.8/dist-packages/abuse_finder/domain.py", line 3, in <module> from pythonwhois.net import get_whois_raw File "/usr/local/lib/python3.8/dist-packages/pythonwhois/__init__.py", line 1, in <module> from . import net, parse File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 363, in <module> registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes] File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 363, in <listcomp> registrant_regexes = [preprocess_regex(regex) for regex in registrant_regexes] File "/usr/local/lib/python3.8/dist-packages/pythonwhois/parse.py", line 205, in preprocess_regex regex = re.sub(r"\\s\*\(\?P<([^>]+)>\.\+\)", r"\s*(?P<\1>\S.*)", regex) File "/usr/lib/python3.8/re.py", line 210, in sub return _compile(pattern, flags).sub(repl, string, count) File "/usr/lib/python3.8/re.py", line 327, in _subx template = _compile_repl(template, pattern) File "/usr/lib/python3.8/re.py", line 318, in _compile_repl return sre_parse.parse_template(repl, pattern) File "/usr/lib/python3.8/sre_parse.py", line 1042, in parse_template raise s.error('bad escape %s' % this, len(this))re.error: bad escape \s at position 0

**Expected behavior**
Does not work Abuse_Finder_3_0

**Work environment**
- Server OS: Ubuntu 20.04.2
- Cortex version: 3.1.0-1
 - Cortex Analyzer/Responder name: Abuse_Finder_3_0
- Cortex Analyzer/Responder version: Abuse_Finder_3_0

**Possible solutions**
I don't know how to cure it yet.

**Comment by BeeruxBash** [comment]
I am having the same error whenever I try to run any observable for analysis, is there any solution to this problem yet?
