### ISSUE TITLE
MISP_2_1

### ISSUE THREAD

**Issue by khalidrehan** [TheHive-Project/Cortex-Analyzers#955]
### Request Type
 Analyzer

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 18.04
| Cortex Analyzer Name      | MISP_2_1
| Cortex Analyzer Version   | Latest.
| Cortex Version            | 3.5

### Description
Error when I use the MISP Analyzer:
`CRITICAL [create_misp_object.py:24 - <module>() ] You need lief >= 0.11.0. The quick and dirty fix is: pip3 install --force pymisp[fileobjects]Traceback (most recent call last):  File "/opt/Cortex-Analyzers/analyzers/MISP/misp.py", line 80, in <module>    MISPAnalyzer().run()  File "/opt/Cortex-Analyzers/analyzers/MISP/misp.py", line 29, in __init__    proxies={'http': self.http_proxy, 'https': self.https_proxy})  File "/opt/Cortex-Analyzers/analyzers/MISP/mispclient.py", line 62, in __init__    proxies=proxies))  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 142, in __init__    if brotli_supported():  File "/usr/local/lib/python3.6/dist-packages/pymisp/api.py", line 97, in brotli_supported    major, minor, patch = urllib3.__version__.split('.')  # noqa: F811ValueError: not enough values to unpack (expected 3, got 2)`

pymisp is installed and working on the MISP server.
Where to look?

**P.S:** VirusTotal and IpInfo are working fine.

Regards,
Khalid.

**Comment by khalidrehan** [comment]
![image](https://user-images.githubusercontent.com/37035465/109691239-4baff400-7b98-11eb-86fb-a6ef67cb9d8c.png)

**Comment by dadokkio** [comment]
Hi, have you tried to follow what is suggested by the error?
`You need lief >= 0.11.0. The quick and dirty fix is: pip3 install --force pymisp[fileobjects]`

**Comment by khalidrehan** [comment]
> Hi, have you tried to follow what is suggested by the error?
> `You need lief >= 0.11.0. The quick and dirty fix is: pip3 install --force pymisp[fileobjects]`

Yes, I did.
I installed both lief and pymisp..

**Comment by dadokkio** [comment]
Ok, the error in pymisp happens when it tries to split urllib3 release. 
A fix for this has been release in pymisp [4 days ago](https://github.com/MISP/PyMISP/commit/59bb0a7bb64804fcf498d31f237c0536f8603410#diff-24ea984f4dba50159301da0922e0c7b1040f43b4eb51c7cd234c284ec651b6fd)
Can you try update it?

**Comment by khalidrehan** [comment]
![image](https://user-images.githubusercontent.com/37035465/109819769-7310ca80-7c45-11eb-87ab-ae6dc49bd4ba.png)
